before:
  hooks:
    - go mod tidy

builds:
  - main: ./main.go
    binary: kubiya-cli-{{ .Os }}-{{ .Arch }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.versionStr={{.Tag}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'

# Disable archives to distribute raw binaries
archives:
  - format: binary
    name_template: >-
      kubiya-cli-{{ .Os }}-{{ .Arch }}
    files: []

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch 