# Site settings
title: Kubiya CLI Documentation
email: support@kubiya.ai
description: >-
  Comprehensive documentation for the Kubiya CLI - Your Agentic Automation Companion.
  Manage serverless agents, workflows, and tools with ease.
baseurl: ""
url: "https://kubiyabot.github.io/cli"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
navigation:
  - title: Home
    url: /
  - title: Quick Start
    url: /pages/quickstart
  - title: Installation
    url: /pages/installation
  - title: Commands
    url: /pages/commands
  - title: Examples
    url: /pages/examples
  - title: MCP Integration
    url: /pages/mcp
  - title: API Reference
    url: /pages/api
  - title: Troubleshooting
    url: /pages/troubleshooting

# Custom variables
github:
  repository_url: https://github.com/kubiyabot/cli
  
# Code highlighting
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true

# Collections
collections:
  examples:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "examples"
    values:
      layout: "example"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/