/*
Kubiya API

Testing RunnersAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package kubiya

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_kubiya_RunnersAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RunnersAPIService V1RunnersGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.RunnersAPI.V1RunnersGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnersAPIService V1RunnersRunnerHealthGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var runner string

		resp, httpRes, err := apiClient.RunnersAPI.V1RunnersRunnerHealthGet(context.Background(), runner).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
