/*
Kubiya API

Testing IntegrationAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package kubiya

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_kubiya_IntegrationAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test IntegrationAPIService V1IntegrationsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.IntegrationAPI.V1IntegrationsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IntegrationAPIService V1IntegrationsVendorDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var vendor string

		resp, httpRes, err := apiClient.IntegrationAPI.V1IntegrationsVendorDelete(context.Background(), vendor).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IntegrationAPIService V1IntegrationsVendorGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var vendor string

		resp, httpRes, err := apiClient.IntegrationAPI.V1IntegrationsVendorGet(context.Background(), vendor).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IntegrationAPIService V1IntegrationsVendorStatusPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var vendor string

		resp, httpRes, err := apiClient.IntegrationAPI.V1IntegrationsVendorStatusPost(context.Background(), vendor).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
