/*
Kubiya API

API documentation for Kubiya

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kubiya

import (
	"encoding/json"
)

// checks if the WhoAmIResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WhoAmIResponse{}

// WhoAmIResponse struct for WhoAmIResponse
type WhoAmIResponse struct {
	Email *string `json:"email,omitempty"`
	Organization *string `json:"organization,omitempty"`
}

// NewWhoAmIResponse instantiates a new WhoAmIResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhoAmIResponse() *WhoAmIResponse {
	this := WhoAmIResponse{}
	return &this
}

// NewWhoAmIResponseWithDefaults instantiates a new WhoAmIResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhoAmIResponseWithDefaults() *WhoAmIResponse {
	this := WhoAmIResponse{}
	return &this
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *WhoAmIResponse) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhoAmIResponse) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *WhoAmIResponse) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *WhoAmIResponse) SetEmail(v string) {
	o.Email = &v
}

// GetOrganization returns the Organization field value if set, zero value otherwise.
func (o *WhoAmIResponse) GetOrganization() string {
	if o == nil || IsNil(o.Organization) {
		var ret string
		return ret
	}
	return *o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhoAmIResponse) GetOrganizationOk() (*string, bool) {
	if o == nil || IsNil(o.Organization) {
		return nil, false
	}
	return o.Organization, true
}

// HasOrganization returns a boolean if a field has been set.
func (o *WhoAmIResponse) HasOrganization() bool {
	if o != nil && !IsNil(o.Organization) {
		return true
	}

	return false
}

// SetOrganization gets a reference to the given string and assigns it to the Organization field.
func (o *WhoAmIResponse) SetOrganization(v string) {
	o.Organization = &v
}

func (o WhoAmIResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WhoAmIResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Organization) {
		toSerialize["organization"] = o.Organization
	}
	return toSerialize, nil
}

type NullableWhoAmIResponse struct {
	value *WhoAmIResponse
	isSet bool
}

func (v NullableWhoAmIResponse) Get() *WhoAmIResponse {
	return v.value
}

func (v *NullableWhoAmIResponse) Set(val *WhoAmIResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWhoAmIResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWhoAmIResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhoAmIResponse(val *WhoAmIResponse) *NullableWhoAmIResponse {
	return &NullableWhoAmIResponse{value: val, isSet: true}
}

func (v NullableWhoAmIResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhoAmIResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


