/*
Kubiya API

API documentation for Kubiya

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kubiya

import (
	"encoding/json"
)

// checks if the V1IntegrationsVendorStatusPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1IntegrationsVendorStatusPostRequest{}

// V1IntegrationsVendorStatusPostRequest struct for V1IntegrationsVendorStatusPostRequest
type V1IntegrationsVendorStatusPostRequest struct {
	Status *string `json:"status,omitempty"`
}

// NewV1IntegrationsVendorStatusPostRequest instantiates a new V1IntegrationsVendorStatusPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1IntegrationsVendorStatusPostRequest() *V1IntegrationsVendorStatusPostRequest {
	this := V1IntegrationsVendorStatusPostRequest{}
	return &this
}

// NewV1IntegrationsVendorStatusPostRequestWithDefaults instantiates a new V1IntegrationsVendorStatusPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1IntegrationsVendorStatusPostRequestWithDefaults() *V1IntegrationsVendorStatusPostRequest {
	this := V1IntegrationsVendorStatusPostRequest{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *V1IntegrationsVendorStatusPostRequest) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1IntegrationsVendorStatusPostRequest) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *V1IntegrationsVendorStatusPostRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *V1IntegrationsVendorStatusPostRequest) SetStatus(v string) {
	o.Status = &v
}

func (o V1IntegrationsVendorStatusPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1IntegrationsVendorStatusPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableV1IntegrationsVendorStatusPostRequest struct {
	value *V1IntegrationsVendorStatusPostRequest
	isSet bool
}

func (v NullableV1IntegrationsVendorStatusPostRequest) Get() *V1IntegrationsVendorStatusPostRequest {
	return v.value
}

func (v *NullableV1IntegrationsVendorStatusPostRequest) Set(val *V1IntegrationsVendorStatusPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1IntegrationsVendorStatusPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1IntegrationsVendorStatusPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1IntegrationsVendorStatusPostRequest(val *V1IntegrationsVendorStatusPostRequest) *NullableV1IntegrationsVendorStatusPostRequest {
	return &NullableV1IntegrationsVendorStatusPostRequest{value: val, isSet: true}
}

func (v NullableV1IntegrationsVendorStatusPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1IntegrationsVendorStatusPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


