name: Build and Publish APT Package

on:
  push:
    branches-ignore:
      - main
      - stable
    paths-ignore:
      - '.git/**'
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y devscripts debhelper dh-make gnupg

      - name: Setup GPG
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import
          # Get the key ID of the imported key
          KEY_ID=$(gpg --list-secret-keys --keyid-format=long | grep -B 1 "costa@kubiya.ai" | head -n 1 | awk '{print $2}' | cut -d'/' -f2)
          # Trust the key ultimately
          echo -e "5\ny\n" | gpg --command-fd 0 --expert --edit-key $KEY_ID trust

      - name: Create Debian package structure
        run: |
          mkdir -p debian
          cat > debian/control << EOF
          Source: kubiya-cli
          Section: utils
          Priority: optional
          Maintainer: Kubiya <support@kubiya.ai>
          Build-Depends: debhelper-compat (= 13), dh-golang, golang-go
          Standards-Version: 4.5.1

          Package: kubiya-cli
          Architecture: any
          Depends: \${shlibs:Depends}, \${misc:Depends}
          Description: Kubiya CLI
           Command line interface for Kubiya AI platform.
          EOF

          cat > debian/rules << EOF
          #!/usr/bin/make -f
          %:
          	dh \$@ --with golang
          EOF

          chmod +x debian/rules

      - name: Build Debian package
        run: |
          dpkg-buildpackage -us -uc -b

      - name: Setup APT repository
        run: |
          mkdir -p apt-repo/apt/dists/stable/main/binary-amd64
          cp ../kubiya-cli_*_amd64.deb apt-repo/apt/pool/main/
          cd apt-repo/apt
          dpkg-scanpackages pool/main /dev/null > dists/stable/main/binary-amd64/Packages
          gzip -9 > dists/stable/main/binary-amd64/Packages.gz < dists/stable/main/binary-amd64/Packages

      - name: Create Release file
        run: |
          cd apt-repo/apt/dists/stable
          cat > Release << EOF
          Origin: Kubiya
          Label: Kubiya APT Repository
          Suite: stable
          Codename: stable
          Version: 1.0
          Architectures: amd64
          Components: main
          Description: APT repository for Kubiya CLI
          EOF

      - name: Sign Release file
        run: |
          cd apt-repo/apt/dists/stable
          KEY_ID=$(gpg --list-secret-keys --keyid-format=long | grep -B 1 "costa@kubiya.ai" | head -n 1 | awk '{print $2}' | cut -d'/' -f2)
          echo "${{ secrets.GPG_PASSPHRASE }}" | gpg --batch --yes --pinentry-mode loopback --passphrase-fd 0 --default-key $KEY_ID --clearsign -o InRelease Release
          echo "${{ secrets.GPG_PASSPHRASE }}" | gpg --batch --yes --pinentry-mode loopback --passphrase-fd 0 --default-key $KEY_ID -abs -o Release.gpg Release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apt-repo
          publish_branch: gh-pages
          force_orphan: true