name: Deploy APT Repository

on:
  push:
    branches:
      - main
    paths:
      - 'apt-repo/**'
      - '.github/workflows/deploy-apt-repo.yml'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apt-repo
          publish_branch: gh-pages
          force_orphan: true 