name: Build Homebrew Formula

on:
  push:
    branches-ignore:
      - main
    # paths-ignore:
    #   - '.git/**'
    #   - '.github/**'

permissions:
  contents: write

jobs:
  build-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CLI repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Build binary
        run: |
          mkdir -p dist
          GOOS=darwin GOARCH=amd64 go build -o dist/kubiya-cli-darwin-amd64 ./main.go

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/kubiya-cli-darwin-amd64
          tag_name: ${{ github.sha }}
          name: Development Build
          body: |
            Development build from commit ${{ github.sha }}
          draft: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.KUBIYA_GITHUB_TOKEN }}

      - name: Get Release URL
        id: get_release_url
        run: |
          RELEASE_URL="https://github.com/${{ github.repository }}/releases/download/${{ github.sha }}/kubiya-cli-darwin-amd64"
          echo "release_url=$RELEASE_URL" >> $GITHUB_OUTPUT

      - name: Generate Homebrew Formula
        run: |
          # Get the current commit SHA for versioning
          VERSION="0.0.0-dev.$(git rev-parse --short HEAD)"
          
          # Calculate SHA256 of the binary
          SHA256=$(shasum -a 256 dist/kubiya-cli-darwin-amd64 | cut -d' ' -f1)
          
          # Create the formula
          mkdir -p Formula
          cat > Formula/kubiya.rb << EOF
          class Kubiya < Formula
            desc "Command line interface for Kubiya AI platform"
            homepage "https://github.com/${{ github.repository }}"
            url "${{ steps.get_release_url.outputs.release_url }}"
            sha256 "${SHA256}"
            version "${VERSION}"
            
            # Specify platform-specific dependencies
            depends_on :macos
            depends_on "go" => :build
            
            def install
              bin.install "kubiya-cli-darwin-amd64" => "kubiya"
            end
            
            test do
              system "#{bin}/kubiya", "--version"
            end
            
            # Add caveats for users
            def caveats
              <<~EOS
                kubiya has been installed as "kubiya".
                
                To get started, run:
                  kubiya --help
              EOS
            end
          end
          EOF

      - name: Checkout Homebrew Tap repository
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.HOMEBREW_TAP_REPO }}
          path: homebrew-tap
          token: ${{ secrets.KUBIYA_GITHUB_TOKEN }}

      - name: Update Homebrew Formula
        run: |
          # Create Formula directory if it doesn't exist
          mkdir -p homebrew-tap/Formula
          
          # Copy the formula
          cp Formula/kubiya.rb homebrew-tap/Formula/
          
          # Configure git
          cd homebrew-tap
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Check if there are changes
          git add Formula/kubiya.rb
          git diff --staged --quiet || HAS_CHANGES=1
          
          if [ "$HAS_CHANGES" ]; then
            git commit -m "Update kubiya formula to version ${VERSION}"
            git push
          else
            echo "No changes to commit."
          fi