name: Build Homebrew Formula

on:
  push:
    branches-ignore:
      - main
    # paths-ignore:
    #   - '.git/**'
    #   - '.github/**'

permissions:
  contents: write

jobs:
  build-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Build binary
        run: |
          mkdir -p dist
          GOOS=darwin GOARCH=amd64 go build -o dist/kubiya-cli-darwin-amd64 ./main.go

      - name: Generate Homebrew Formula
        run: |
          # Get the current commit SHA for versioning
          VERSION="0.0.0-dev.$(git rev-parse --short HEAD)"
          
          # Calculate SHA256 of the binary
          SHA256=$(shasum -a 256 dist/kubiya-cli-darwin-amd64 | cut -d' ' -f1)
          
          # Create the formula
          mkdir -p Formula
          cat > Formula/kubiya.rb << EOF
          class Kubiya < Formula
            desc "Command line interface for Kubiya AI platform"
            homepage "https://github.com/${{ github.repository }}"
            url "https://github.com/${{ github.repository }}/releases/download/${VERSION}/kubiya-cli-darwin-amd64"
            sha256 "${SHA256}"
            version "${VERSION}"
            
            def install
              bin.install "kubiya-cli-darwin-amd64" => "kubiya"
            end
            
            test do
              system "#{bin}/kubiya", "--version"
            end
          end
          EOF

      - name: Create Homebrew Tap Repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Clone the Homebrew tap repository
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ secrets.HOMEBREW_TAP_REPO }}.git homebrew-tap
          
          # Copy the formula
          cp Formula/kubiya.rb homebrew-tap/Formula/
          
          # Commit and push
          cd homebrew-tap
          git add Formula/kubiya.rb
          git commit -m "Update kubiya formula to version ${VERSION}"
          git push 