name: Build - main

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '.git/**'

concurrency:
  group: ${{ github.repository }}-build-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build binaries
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/kubiya-linux-amd64 ./main.go
          GOOS=linux GOARCH=arm64 go build -o dist/kubiya-linux-arm64 ./main.go
          GOOS=darwin GOARCH=amd64 go build -o dist/kubiya-darwin-amd64 ./main.go
          GOOS=darwin GOARCH=arm64 go build -o dist/kubiya-darwin-arm64 ./main.go
          GOOS=windows GOARCH=amd64 go build -o dist/kubiya-windows-amd64.exe ./main.go
          cd dist && sha256sum * > checksums.txt

      - name: Upload binaries as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kubiya-cli-binaries
          path: dist/*
          retention-days: 5

      - name: Set up GitHub SHA
        id: set-short-sha
        run: |
          echo "SHA_SHORT=${GITHUB_SHA: -5}" >> $GITHUB_ENV
          echo "sha_short=${GITHUB_SHA: -5}" >> $GITHUB_OUTPUT

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,prefix=sha-,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
