name: Create and publish a Docker image - TAG

on:
  push:
    tags:
      - '*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            ${{ github.ref_name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # Build and upload binaries only on tag releases
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build release binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -o kubiya-linux-amd64 ./cmd/kubiya/main.go
          GOOS=linux GOARCH=arm64 go build -o kubiya-linux-arm64 ./cmd/kubiya/main.go
          GOOS=darwin GOARCH=amd64 go build -o kubiya-darwin-amd64 ./cmd/kubiya/main.go
          GOOS=darwin GOARCH=arm64 go build -o kubiya-darwin-arm64 ./cmd/kubiya/main.go
          GOOS=windows GOARCH=amd64 go build -o kubiya-windows-amd64.exe ./cmd/kubiya/main.go

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            kubiya-linux-amd64
            kubiya-linux-arm64
            kubiya-darwin-amd64
            kubiya-darwin-arm64
            kubiya-windows-amd64.exe
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::564407622114:role/github-action-role

      - name: Update kubiya_versions.json
        run: |
          aws s3 cp s3://kubiya-cli/stable/kubiya_versions.json kubiya_versions.json || echo "{}" > kubiya_versions.json
          sed -i 's|"'"${{ env.REPO_NAME }}"'": *"[^"]*"|"'"${{ env.REPO_NAME }}"'": "'"${{ env.REGISTRY }}/kubiyabot/${{ env.REPO_NAME }}:${{ github.ref_name }}"'"|' kubiya_versions.json
          aws s3 cp kubiya_versions.json s3://kubiya-cli/stable/kubiya_versions.json --acl public-read 